[user]
name = "Filip Pękala"
email = "272985@student.pwr.edu.pl"

[ui]
movement.edit = true
editor = "nvim"
default-command = "log"
pager = ["less", "-RXF"]

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[core]
fsmonitor = "watchman"
watchman.register-snapshot-trigger = true
