# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "nvidia" "i915" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];
  boot.kernelModules = [ "kvm-intel" "uinput" ];
	boot.kernelParams = [ "nvidia-drm.fbdev=1" ];
	#boot.blacklistedKernelModules = ["nouveau" "nvidiafb"];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1f80ba96-ad6d-4c68-86c2-83d4d9734e30";
      fsType = "ext4";
    };
  fileSystems."/mnt/data" = {
    device = "/dev/data/data";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/add67558-a735-4723-96ba-ea5e54856ecd"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  #nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics.enable = true;
	#hardware.opengl = {

	#	enable = true;
	#	#driSupport = true;
	#	#driSupport32Bit = true;
	#	extraPackages = with pkgs; [ vaapiVdpau ];
	#};

	services.xserver.videoDrivers = ["nvidia"];

	hardware.nvidia = {
		powerManagement.enable = true;
		powerManagement.finegrained = false;
		modesetting.enable = true;
		#nvidiaPersistenced = true;
		nvidiaSettings = true;
		open = false;
		#package = config.boot.kernelPackages.nvidiaPackages.mkDriver {
		#	version = "550.40.07";
		#	sha256_64bit = "sha256-KYk2xye37v7ZW7h+uNJM/u8fNf7KyGTZjiaU03dJpK0=";
		#	sha256_aarch64 = "sha256-AV7KgRXYaQGBFl7zuRcfnTGr8rS5n13nGUIe3mJTXb4=";
		#	openSha256 = "sha256-mRUTEWVsbjq+psVe+kAT6MjyZuLkG2yRDxCMvDJRL1I=";
		#	settingsSha256 = "sha256-c30AQa4g4a1EHmaEu1yc05oqY01y+IusbBuq+P6rMCs=";
		#	persistencedSha256 = "sha256-11tLSY8uUIl4X/roNnxf5yS2PQvHvoNjnd2CB67e870=";
		#};
		package = config.boot.kernelPackages.nvidiaPackages.production;
	};
}
